### ISSUE TITLE
这个demo的photo的流程能走通吗 ，我这里报错了；com.baidu.paddledetection.detection E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker     Process: com.baidu.paddledetection.detection, PID: 7235     java.lang.UnsatisfiedLinkError: dlopen failed: library "libhiai_ir.so" not found: needed by /data/app/~~cgK9wkYPijT5hSlcT7zZUg==/com.baidu.paddledetection.detection-72gghyv30YKLyeEOvt2HNA==/base.apk!/lib/arm64-v8a/libpaddle_lite_jni.so in namespace classloader-namespace

### ISSUE THREAD

**Issue by yatouxingren** [marsplus-wjh/Picodet-PaddleLite-AndroidDemo#4]
将跳转photofragment的方式打开后，有如下报错：主要是在Predictor.java中的loadmodel环节 这句话paddlePredictor = PaddlePredictor.createPaddlePredictor(config);报错了：

2021-12-21 21:57:08.241 7619-8176/com.baidu.paddledetection.detection E/AndroidRuntime: FATAL EXCEPTION: Predictor Worker
    Process: com.baidu.paddledetection.detection, PID: 7619
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libhiai_ir.so" not found: needed by /data/app/~~lxmt6XinqrhIwWajIpNunA==/com.baidu.paddledetection.detection-Ws6TO34Pr--GImdhBZjrFA==/base.apk!/lib/arm64-v8a/libpaddle_lite_jni.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1665)
        at com.baidu.paddle.lite.PaddleLiteInitializer.init(PaddleLiteInitializer.java:20)
        at com.baidu.paddle.lite.PaddlePredictor.<clinit>(PaddlePredictor.java:197)
        at com.baidu.paddle.lite.PaddlePredictor.createPaddlePredictor(PaddlePredictor.java:41)
        at com.baidu.paddledetection.detection.Predictor.loadModel(Predictor.java:131)
        at com.baidu.paddledetection.detection.Predictor.init(Predictor.java:78)
        at com.baidu.paddledetection.detection.PhotoFragment.onLoadModel(PhotoFragment.java:189)
        at com.baidu.paddledetection.detection.PhotoFragment$2.handleMessage(PhotoFragment.java:124)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:228)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by marsplus-wjh** [comment]
photo 暂不支持，主要是 photo 部分是 java 的需要将 picodet 前后处理都改成 java 的，目前还没有完成

**Comment by yatouxingren** [comment]
> photo 暂不支持，主要是 photo 部分是 java 的需要将 picodet 前后处理都改成 java 的，目前还没有完成

这个近期有计划吗，希望能早点支持啊
